#!/usr/bin/env python
from optparse import OptionParser
import sys
import os

meshtemplate='''
Point(1) = {0, 0, 0, <dx>};
Extrude {1, 0, 0} {
  Point{1}; Layers{<layers>};
}
Extrude {0, 1, 0} {
  Line{1}; Layers{<layers>};
}
'''

def generate_meshfile(name,layers):


    file(name+".geo",'w').write(
        meshtemplate.replace('<dx>',str(1./layers)
                 ).replace('<layers>',str(layers)))

    os.system("gmsh -2 "+name+".geo")
    os.system("./gmsh2triangle --2d "+name+".msh")

#####################################################################
# Script starts here.
optparser=OptionParser(usage='usage: %prog [options] <name> <layers>',
                       add_help_option=True,
                       description="""Generate the mesh files for a given"""+
                       """number of layers of elements in the channel.""")

(options, argv) = optparser.parse_args()

try:
    name=argv[0]
    layers=int(argv[1])
except:
    optparser.print_help()
    sys.exit(1)

sys.path.append(".")

generate_meshfile(name,layers)
