# # TODO: If we can apt install almost everything then we don't need this extra container.
#
# DockerFile for an environment into which firedrake can be installed.

FROM ubuntu:24.04

# Update and install required packages for Firedrake
USER root
SHELL ["/bin/bash", "-o", "pipefail", "-c"]

RUN apt-get update \
    && apt-get -y dist-upgrade \
    && DEBIAN_FRONTEND=noninteractive apt-get -y install tzdata \
    && wget https://raw.githubusercontent.com/firedrakeproject/firedrake/connorjward/pip-install/scripts/firedrake-system-deps
    && apt-get -y install $(python firedrake-system-deps) \
    && rm -rf /var/lib/apt/lists/*

# Use a more sane locale
ENV LC_ALL C.UTF-8

# Change the `ubuntu` user to `firedrake`
# and ensure that we do not run as root on self-hosted systems
RUN usermod -d /home/firedrake -m ubuntu && \
    usermod -l firedrake ubuntu && \
    groupmod -n firedrake ubuntu && \
    usermod -aG sudo firedrake && \
    echo "firedrake:docker" | chpasswd && \
    echo "firedrake ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers && \
    ldconfig

USER firedrake
WORKDIR /home/firedrake

# Fetch PETSc and SLEPc
RUN git clone https://github.com/firedrakeproject/petsc.git \
    && git clone https://github.com/firedrakeproject/slepc.git

RUN bash -c 'cd petsc; \
    ./configure \
        --COPTFLAGS=-O3 -march=native -mtune=native \
        --CXXOPTFLAGS=-O3 -march=native -mtune=native \
        --FOPTFLAGS=-O3 -march=native -mtune=native \
        --with-c2html=0 \
        --with-debugging=0 \
        --with-fortran-bindings=0 \
        --with-make-np=12 \
        --with-shared-libraries=1 \
        --with-zlib \
        --with-hdf5 \
        --with-hwloc \
        --with-ptscotch \
        --with-scalapack \
        --with-fftw \
        --with-hypre \
        --with-metis \
        --with-mumps \
        --with-netcdf \
        --with-pnetcdf \
        --download-pastix \
        --with-suitesparse \
        --with-superlu_dist \
        --with-strict-petscerrorcode \
        PETSC_ARCH=packages; \
        mv packages/include/petscconf.h packages/include/old_petscconf.nope; \
        rm -rf /home/firedrake/petsc/**/externalpackages; \
        rm -rf /home/firedrake/petsc/src/docs; \
        rm -f /home/firedrake/petsc/src/**/tutorials/output/*; \
        rm -f /home/firedrake/petsc/src/**/tests/output/*'
# Don't run make here, we only want the external packages
# It is also necessary to move `petscconf.h` so packages isn't treated like a working PETSc
# Cleaned up unnecessary files

# Build default Firedrake PETSc
RUN bash -c 'export PACKAGES=/home/firedrake/petsc/packages; \
    cd petsc; \
    ./configure \
        --COPTFLAGS=-O3 -march=native -mtune=native \
        --CXXOPTFLAGS=-O3 -march=native -mtune=native \
        --FOPTFLAGS=-O3 -march=native -mtune=native \
        --with-c2html=0 \
        --with-debugging=0 \
        --with-fortran-bindings=0 \
        --with-make-np=12 \
        --with-shared-libraries=1 \
        --with-bison \
        --with-flex \
        --with-zlib \
        --with-fftw-dir=$PACKAGES \
        --with-hdf5-dir=$PACKAGES \
        --with-hwloc-dir=$PACKAGES \
        --with-hypre-dir=$PACKAGES \
        --with-metis-dir=$PACKAGES \
        --with-mpi-dir=$PACKAGES \
        --with-mumps-dir=$PACKAGES \
        --with-netcdf-dir=$PACKAGES \
        --with-pastix-dir=$PACKAGES \
        --with-pnetcdf-dir=$PACKAGES \
        --with-ptscotch-dir=$PACKAGES \
        --with-scalapack-dir=$PACKAGES \
        --with-suitesparse-dir=$PACKAGES \
        --with-superlu_dist-dir=$PACKAGES \
        --with-strict-petscerrorcode \
        PETSC_ARCH=default; \
    make PETSC_DIR=/home/firedrake/petsc PETSC_ARCH=default all;'

# Build default Firedrake SLEPc
RUN bash -c 'cd slepc; \
    ./configure; \
    make SLEPC_DIR=/home/firedrake/slepc PETSC_DIR=/home/firedrake/petsc PETSC_ARCH=default;'

# Additionally build complex PETSc for Firedrake
RUN bash -c 'export PACKAGES=/home/firedrake/petsc/packages; \
    cd petsc; \
    ./configure \
        --COPTFLAGS=-O3 -march=native -mtune=native \
        --CXXOPTFLAGS=-O3 -march=native -mtune=native \
        --FOPTFLAGS=-O3 -march=native -mtune=native \
        --with-c2html=0 \
        --with-debugging=0 \
        --with-fortran-bindings=0 \
        --with-make-np=12 \
        --with-scalar-type=complex \
        --with-shared-libraries=1 \
        --with-bison \
        --with-flex \
        --with-zlib \
        --with-fftw-dir=$PACKAGES \
        --with-hdf5-dir=$PACKAGES \
        --with-hwloc-dir=$PACKAGES \
        --with-metis-dir=$PACKAGES \
        --with-mpi-dir=$PACKAGES \
        --with-mumps-dir=$PACKAGES \
        --with-netcdf-dir=$PACKAGES \
        --with-pastix-dir=$PACKAGES \
        --with-pnetcdf-dir=$PACKAGES \
        --with-ptscotch-dir=$PACKAGES \
        --with-scalapack-dir=$PACKAGES \
        --with-suitesparse-dir=$PACKAGES \
        --with-superlu_dist-dir=$PACKAGES \
        --with-strict-petscerrorcode \
        PETSC_ARCH=complex; \
    make PETSC_DIR=/home/firedrake/petsc PETSC_ARCH=complex all;'

# Build complex Firedrake SLEPc
RUN bash -c 'export PETSC_DIR=/home/firedrake/petsc; \
    export PETSC_ARCH=complex; \
    cd slepc; \
    ./configure; \
    make SLEPC_DIR=/home/firedrake/slepc PETSC_DIR=/home/firedrake/petsc PETSC_ARCH=complex;'

# Set some useful environment variables
ENV PETSC_DIR /home/firedrake/petsc
ENV SLEPC_DIR /home/firedrake/slepc
ENV MPICH_DIR /home/firedrake/petsc/packages/bin
ENV HDF5_DIR /home/firedrake/petsc/packages
ENV HDF5_MPI ON
ENV OMP_NUM_THREADS 1
ENV OPENBLAS_NUM_THREADS 1
