# Dockerfile for an environment into which firedrake can be installed.

FROM ubuntu:latest

# Set '-o pipefail' to avoid linter error (https://github.com/hadolint/hadolint/wiki/DL4006)
SHELL ["/bin/bash", "-o", "pipefail", "-c"]

# Use a more sane locale
ENV LC_ALL=C.UTF-8

# Avoid tzdata prompt
# (https://stackoverflow.com/questions/61388002/how-to-avoid-question-during-the-docker-build)
ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Europe/London

# Install 'parallel' because it is needed by 'firedrake-run-split-tests'
RUN apt-get update \
    && apt-get -y install curl parallel python3 python3-pip python3-venv \
    && rm -rf /var/lib/apt/lists/*

ENV OMP_NUM_THREADS=1
ENV OPENBLAS_NUM_THREADS=1
