# Dockerfile for an environment into which firedrake can be installed.

FROM ubuntu:latest

# Set '-o pipefail' to avoid linter error (https://github.com/hadolint/hadolint/wiki/DL4006)
SHELL ["/bin/bash", "-o", "pipefail", "-c"]

# Use a more sane locale
ENV LC_ALL=C.UTF-8

# Avoid tzdata prompt
# (https://stackoverflow.com/questions/61388002/how-to-avoid-question-during-the-docker-build)
ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Europe/London

# Install 'parallel' because it is needed by 'firedrake-run-split-tests'
RUN apt-get update \
    && apt-get -y install curl parallel python3 python3-venv sudo \
    && rm -rf /var/lib/apt/lists/*

# Change the `ubuntu` user to `firedrake`
# and ensure that we do not run as root on self-hosted systems
RUN usermod -d /home/firedrake -m ubuntu \
    && usermod -l firedrake ubuntu \
    && groupmod -n firedrake ubuntu \
    && usermod -aG sudo firedrake \
    && echo "firedrake:docker" | chpasswd \
    && echo "firedrake ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers \
    && ldconfig

USER firedrake
WORKDIR /home/firedrake

ENV OMP_NUM_THREADS=1
ENV OPENBLAS_NUM_THREADS=1
