# Dockerfile for Firedrake plus packages needed to build the documentation

# UNDO ME
# FROM firedrakeproject/firedrake-vanilla-default:latest
FROM firedrakeproject/firedrake-vanilla-default:piptest

RUN sudo apt-get update \
    && sudo apt-get -y install inkscape texlive-full \
    && sudo rm -rf /var/lib/apt/lists/*
