# -*- coding: utf-8 -*-
#
# Firedrake documentation build configuration file, created by
# sphinx-quickstart on Sat Jun 29 19:06:45 2013.
#
# This file is execfile()d with the current directory set to its containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#sys.path.insert(0, os.path.abspath('.'))

# -- General configuration -----------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be extensions
# coming with Sphinx (named 'sphinx.ext.*') or your custom ones.
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.extlinks',
    'sphinx.ext.mathjax',
    'sphinx.ext.intersphinx',
    'sphinx.ext.viewcode',
    'sphinx.ext.graphviz',
    'sphinxcontrib.jquery',
    'sphinxcontrib.youtube',
    'sphinxcontrib.bibtex',
    'sphinxcontrib.inkscapeconverter',
    'sphinx.ext.napoleon',
]

mathjax_path = 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.2/es5/tex-mml-chtml.min.js'

mathjax3_config = {
    'loader': {'load': ['[tex]/mathtools']},
    'tex': {'packages': {'[+]': ['mathtools']}}
}

# Both the class’ and the __init__ method’s docstring are concatenated and
# inserted into the class definition
autoclass_content = 'both'

# Document __call__ methods
autodoc_default_options = {
    'special-members': '__call__'
}

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix of source filenames.
source_suffix = '.rst'

# The encoding of source files.
#source_encoding = 'utf-8-sig'

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = u'Firedrake'

# Author
from configparser import ConfigParser, ExtendedInterpolation

team = ConfigParser(interpolation=ExtendedInterpolation())
team.optionxform = lambda x: x
team.read('team.ini')

author_list = list(team['active-team'].keys())
author_list += list(team['inactive-team'].keys())
author = ', '.join(author_list)

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
import firedrake
version = "%d.%d" % firedrake.__version_info__[0:2]
# The full version, including alpha/beta/rc tags.
release = firedrake.__version__

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#language = None

# There are two options for replacing |today|: either, you set today to some
# non-false value, then it is used:
#today = ''
# Else, today_fmt is used as the format for a strftime call.
#today_fmt = '%B %d, %Y'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = ['old_pyop2']

# The reST default role (used for this markup: `text`) to use for all documents.
#default_role = None

# If true, '()' will be appended to :func: etc. cross-reference text.
#add_function_parentheses = True

# If true, the current module name will be prepended to all description
# unit titles (such as .. function::).
#add_module_names = True

# If true, sectionauthor and moduleauthor directives will be shown in the
# output. They are ignored by default.
#show_authors = False

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# A list of ignored prefixes for module index sorting.
#modindex_common_prefix = []

# Warn about all references where the target cannot be found
nitpicky = True
nitpick_ignore_regex = [
    # Ignore missing docs from external dependencies
    (r'py:.*', r'dolfin_adjoint_common\..*'),
    (r'py:.*', r'pyadjoint\..*'),
    (r'py:.*', r'tsfc\..*'),
    (r'py:.*', r'ufl\..*'),
    (r'py:.*', r'PETSc\..*'),
    (r'py:.*', r'progress\..*'),
    # Ignore undocumented PyOP2
    ('py:class', 'pyop2.caching.Cached'),
    # Ignore mission docs from Firedrake internal "private" code
    # Any "Base" class eg:
    #   firedrake.adjoint.checkpointing.CheckpointBase
    #   firedrake.slate.slate.TensorBase
    #   firedrake.preconditioners.patch.PatchBase
    ('py:class', r'(firedrake\.)*(.*\.)+.*Base'),
    # Slate Binary- and Unary- OPs
    ('py:class', r'(firedrake\.)*(slate\.)+(.*Op)'),
    ('py:class', 'firedrake.solving_utils._SNESContext'),
    # Pyadjoint BlockVariable is not properly referenced in pyadjoint
    ('py:class', 'BlockVariable'),
]

# Dodgy links
linkcheck_ignore = [
    r'https://doi\.org/.*',
    r'https://epubs\.siam\.org/doi/.*',
    r'https://www\.apl\.washington\.edu/',
    r'https://asmedigitalcollection\.asme\.org/',
    r'https://ieeexplore\.ieee\.org/document/1634311/',
    r'http://www.cs.virginia.edu/stream/',
    r'https://www.sciencedirect.com',
    r'https://.*\.baylor\.edu.*',
    r'https://www.tuomaskarna.com',
    r'https://www.crosscountrytrains.co.uk/',
    r'https://www.siam.org/',
]
linkcheck_timeout = 30

# -- Options for HTML output ---------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
html_theme = 'firedrake'

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#html_theme_options = {}

# Add any paths that contain custom themes here, relative to this directory.
html_theme_path = ['_themes']

# The name for this set of Sphinx documents.  If None, it defaults to
# "<project> v<release> documentation".
#html_title = None

# A shorter title for the navigation bar.  Default is the same as html_title.
#html_short_title = None

# The name of an image file (relative to this directory) to place at the top
# of the sidebar.
#html_logo = None

# The name of an image file (within the static path) to use as favicon of the
# docs.  This file should be a Windows icon file (.ico) being 16x16 or 32x32
# pixels large.
#html_favicon = None

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# If not '', a 'Last updated on:' timestamp is inserted at every page bottom,
# using the given strftime format.
#html_last_updated_fmt = '%b %d, %Y'

# If true, SmartyPants will be used to convert quotes and dashes to
# typographically correct entities.
# html_use_smartypants = True

# Custom sidebar templates, maps document names to template names.
#html_sidebars = {}

# Additional templates that should be rendered to pages, maps page names to
# template names.
#html_additional_pages = {}

# If false, no module index is generated.
#html_domain_indices = True

# If false, no index is generated.
#html_use_index = True

# If true, the index is split into individual pages for each letter.
#html_split_index = False

# If true, links to the reST sources are added to the pages.
#html_show_sourcelink = True

# If true, "Created using Sphinx" is shown in the HTML footer. Default is True.
html_show_sphinx = False

# If true, "(C) Copyright ..." is shown in the HTML footer. Default is True.
html_show_copyright = False

# If true, an OpenSearch description file will be output, and all pages will
# contain a <link> tag referring to it.  The value of this option must be the
# base URL from which the finished HTML is served.
#html_use_opensearch = ''

# This is the file name suffix for HTML files (e.g. ".xhtml").
#html_file_suffix = None

# Output file base name for HTML help builder.
htmlhelp_basename = 'Firedrakedoc'


# -- Options for LaTeX output --------------------------------------------

import os
watermark = os.environ.get('FIREDRAKE_MANUAL_RELEASE')

latex_additional_files = [
    '_static/sphinxpoptitle.sty'
]

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    'papersize': 'a4paper',

    # The font size ('10pt', '11pt' or '12pt').
    'pointsize': '11pt',

    'babel': r'\usepackage[british]{babel}',

    # Additional stuff for the LaTeX preamble.
    'preamble': r'''\newcommand{\require}[1]{}
\usepackage{cancel}

% \sphinxDUC{2730}{\ding{80}}
\sphinxDUC{27F6}{$\rightarrow$}
\sphinxDUC{2208}{$\in$}
\sphinxDUC{2200}{$\forall$}
\sphinxDUC{2218}{$\circ$}
\sphinxDUC{22C5}{$\cdot$}
\sphinxDUC{25A3}{$\boxdot$}
\sphinxDUC{03BB}{$\lambda$}
\sphinxDUC{0393}{$\Gamma$}
% Sphinx equivalent of
% \DeclareUnicodeCharacter{}{}

% Make text sans-serif
\renewcommand{\familydefault}{\sfdefault}

% The default sphinx colouring colours a lot of links that are actually dead in
% the book version.
\definecolor{internallinkcolor}{HTML}{c52b03}
\definecolor{externallinkcolor}{HTML}{e55d05}
%\hypersetup{linkcolor=internallinkcolor}
\hypersetup{linkcolor=black}
%\hypersetup{urlcolor=externallinkcolor}
\hypersetup{urlcolor=black}
\usepackage{sphinxpoptitle}
\subtitle{}
\edition{2023}
'''
f'''
% Mark non-release versions with draft
\\usepackage{{draftwatermark}}
\DraftwatermarkOptions{{
stamp={str(not bool(watermark)).lower()},
angle=90,
scale=0.5,
fontsize=0.1\paperwidth,
text={{DRAFT {release}}},
hpos=0.05\paperwidth
}}

% Hacky way to add all metadata, neither tool sets all fields
\hypersetup{{pdfinfo={{
Title={{Firedrake User Manual}},
Subject={{Mathematics}},
}}}}
\pdfinfo{{
/Author ({author})
/Keywords (Firedrake, Partial Differential Equations, PDEs, Finite Element, FEM, Code Generation)
}}
''',

    'extrapackages': r'''\usepackage{mathtools}''',

    'maketitle': r'\sphinxpoptitlepages',

    'makeindex': r'\usepackage[columns=1]{idxlayout}\makeindex',

    'maxlistdepth' : '8'
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title, author, documentclass [howto/manual]).
latex_documents = [
    ('book', 'Firedrake.tex', u'Firedrake User Manual', r' \and \\'.join(author_list), 'manual'),
]

# The name of an image file (relative to this directory) to place at the top of
# the title page.
latex_logo = '_themes/firedrake/static/banner.png'

# For "manual" documents, if this is true, then toplevel headings are parts,
# not chapters.
#latex_use_parts = False

# If true, show page references after internal links.
#latex_show_pagerefs = False

# If true, show URL addresses after external links.
#latex_show_urls = False

# Documents to append as an appendix to all manuals.
#latex_appendices = []

# If false, no module index is generated.
#latex_domain_indices = True
latex_docclass = {"manual": "book"}


# -- Options for manual page output --------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    ('index', 'firedrake', u'Firedrake Documentation', author, 1)
]

# If true, show URL addresses after external links.
#man_show_urls = False


# -- Options for Texinfo output ------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [(
    'index',
    'Firedrake',
    u'Firedrake Documentation',
    author,
    'Firedrake',
    'One line description of project.',
    'Miscellaneous'
),]

# Documents to append as an appendix to all manuals.
#texinfo_appendices = []

# If false, no module index is generated.
#texinfo_domain_indices = True

# How to display URL addresses: 'footnote', 'no', or 'inline'.
#texinfo_show_urls = 'footnote'

# -- Options for intersphinx ---------------------------------------------

intersphinx_mapping = {
    'pyop2': ('https://op2.github.io/PyOP2', None),
    'ufl': ('https://fenics.readthedocs.io/projects/ufl/en/latest/', None),
    'FIAT': ('https://fenics.readthedocs.io/projects/fiat/en/latest/', None),
    'FInAT': ('https://finat.github.io/FInAT/', None),
    'mpi4py': ('https://mpi4py.readthedocs.io/en/stable/', None),
    'h5py': ('http://docs.h5py.org/en/latest/', None),
    'h5py.h5p': ('https://api.h5py.org/', None),
    'matplotlib': ('https://matplotlib.org/', None),
    'python': ('https://docs.python.org/3/', None),
    'pyadjoint': ('https://www.dolfin-adjoint.org/en/latest/', None),
    'numpy': ('https://numpy.org/doc/stable/', None),
    'loopy': ('https://documen.tician.de/loopy/', None),
    'torch': ('https://pytorch.org/docs/stable/', None),
    'jax': ('https://jax.readthedocs.io/en/latest/', None),
}

#  -- Options for sphinxcontrib.bibtex ------------------------------------
bibtex_bibfiles = ['demos/demo_references.bib', '_static/bibliography.bib', '_static/firedrake-apps.bib', '_static/references.bib']

#  -- Options for sphinx.ext.extlinks ------------------------------------
extlinks = {
    'demo': ('https://firedrakeproject.org/demos/%s', None)
}
