name: Install Firedrake

inputs:
  os:
    description: Operating system (linux or macos)
    type: string
    required: true
  source_ref:
    description: The source branch
    type: string
    required: true
  target_branch:
    description: The target branch (usually 'main' or 'release')
    type: string
    required: true
  arch:
    description: Firedrake configuration to build
    type: string
    required: true
  root_dir:
    description: Base directory
    type: string
    required: true
  np:
    description: Available parallelism
    type: string
    required: true
  deps:
    description: Optional dependencies to install along with Firedrake
    type: string
    required: true

runs:
  using: composite
  steps:
    - name: Pre-run cleanup
      shell: bash
      # Make sure the current directory is empty
      run: find . -delete

    - uses: actions/checkout@v5
      shell: bash
      with:
        path: firedrake-repo
        ref: ${{ inputs.source_ref }}

    - name: Install system dependencies
      shell: bash
      run: |
        if [ ${{ inputs.os }} = 'linux' ]; then
          apt-get -y install \
            $(python3 ./firedrake-repo/scripts/firedrake-configure --arch ${{ matrix.arch }} --show-system-packages)
          apt-get -y install python3-venv
          : # Dependencies needed to run the test suite
          apt-get -y install fonts-dejavu graphviz graphviz-dev parallel poppler-utils
        else
          brew install $(python3 ./firedrake-repo/scripts/firedrake-configure --arch default --show-system-packages)
        fi

    - name: Validate single source of truth
      shell: bash
      run: ./firedrake-repo/scripts/check-config

    # Check that the Dockerfile is using the latest Ubuntu version.
    # The version is hardcoded into the Dockerfile so that the OS
    # for each release is fixed.
    - name: Check Dockerfile Ubuntu version
      shell: bash
      run: |
        latest_version=$(grep "VERSION_ID=" /etc/os-release | cut -d '"' -f 2)
        docker_version=$(grep FROM firedrake-repo/docker/Dockerfile.vanilla | cut -d ':' -f 2)
        echo "Latest version: $latest_version"
        echo "Docker version: $docker_version"
        if [[ "$docker_version" != "$latest_version" ]]; then
          echo "Ubuntu version ${docker_version} in Dockerfile is out of date with latest version ${latest_version}"
          exit 1
        fi

    - name: Install PETSc
      shell: bash
      run: |
        if [ ${{ inputs.target_branch }} = 'release' ]; then
          git clone --depth 1 \
            --branch $(python3 ./firedrake-repo/scripts/firedrake-configure --show-petsc-version) \
            https://gitlab.com/petsc/petsc.git
        else
          git clone --depth 1 https://gitlab.com/petsc/petsc.git
        fi
        cd petsc
        python3 ../firedrake-repo/scripts/firedrake-configure \
          --arch ${{ inputs.arch }} --show-petsc-configure-options | \
          xargs -L1 ./configure --with-make-np=${{ inputs.np }} --download-slepc
        make PETSC_DIR=${{ inputs.root_dir }}/petsc PETSC_ARCH=arch-firedrake-${{ inputs.arch }}
        make check
        {
          echo "PETSC_DIR=${{ inputs.root_dir }}/petsc"
          echo "PETSC_ARCH=arch-firedrake-${{ inputs.arch }}"
          echo "SLEPC_DIR=${{ inputs.root_dir }}/petsc/arch-firedrake-${{ inputs.arch }}"
        } >> "$GITHUB_ENV"

    - name: Install Firedrake
      shell: bash
      run: |
        export $(python3 ./firedrake-repo/scripts/firedrake-configure --arch "${{ matrix.arch }}" --show-env)
        python3 -m venv venv
        . venv/bin/activate

        : # Empty the pip cache to ensure that everything is compiled from scratch
        pip cache purge

        if [ ${{ inputs.target_branch }} = 'release' ]; then
          EXTRA_BUILD_ARGS=''
          EXTRA_PIP_FLAGS=''
        else
          : # Install build dependencies
          pip install "$PETSC_DIR"/src/binding/petsc4py
          pip install -r ./firedrake-repo/requirements-build.txt

          : # Install runtime dependencies that have been removed from the pyproject.toml
          : # because they rely on non-PyPI versions of petsc4py.
          pip install --no-build-isolation --no-deps \
            "$PETSC_DIR"/"$PETSC_ARCH"/externalpackages/git.slepc/src/binding/slepc4py
          pip install --no-deps git+https://github.com/NGSolve/ngsPETSc.git netgen-mesher netgen-occt

          : # We have to pass '--no-build-isolation' to use a custom petsc4py
          EXTRA_BUILD_ARGS='--no-isolation'
          EXTRA_PIP_FLAGS='--no-build-isolation'
        fi

        : # Install from an sdist so we can make sure that it is not ill-formed
        pip install build
        python -m build ./firedrake-repo --sdist $EXTRA_BUILD_ARGS

        pip install --verbose $EXTRA_PIP_FLAGS \
          --no-binary h5py \
          --extra-index-url https://download.pytorch.org/whl/cpu \
          "$(echo ./firedrake-repo/dist/firedrake-*.tar.gz)[${{ inputs.deps }}]"

        firedrake-clean
        pip list
