#!/usr/bin/env python

from firedrake.ffc_interface import clear_cache, FFCKernel
from firedrake.mesh import _clear_cachedir as clear_mesh_cache, _cachedir as mesh_cachedir
from pyop2.compilation import clear_cache as pyop2_clear_cache


if __name__ == '__main__':
    print 'Removing cached ffc kernels from %s' % FFCKernel._cachedir
    clear_cache()
    print 'Removing cached generated meshes from %s' % mesh_cachedir
    clear_mesh_cache()
    pyop2_clear_cache(prompt=True)
