#!/usr/bin/env python3

"""Script for preparing an environment to install Firedrake into."""

# To avoid the pitfalls inherent in having executable configuration files
# this script is intentionally extremely dumb. All configure options are computed
# 'statically' (at import) and the only run-time logic that happens is dispatching
# on the right package manager and arch.

# As a matter of policy, new package managers and archs should only be added to
# this file if they are *tested in CI*.

import sys
import time


def stdout(msg: str, **kwargs) -> None:
    """Write to stdout."""
    print(msg, file=sys.stdout, **kwargs)


def pipe(msg: str, **kwargs) -> None:
    """Print a message to stdout and stop the script."""
    stdout(msg, **kwargs)
    exit(0)


def stderr(msg: str, **kwargs) -> None:
    """Write to stderr."""
    print(msg, file=sys.stderr, **kwargs)


def abort() -> None:
    """Terminate the script."""
    exit(1)


def error(msg: str, **kwargs):
    """Print an error message to stderr and stop the script.

    To make it distinct in the terminal output, messages are prefixed with 'ERROR: '.

    """
    stderr(f"ERROR: {msg}", **kwargs)
    # wait so users have a chance to see the message before it gets swamped by stdout
    time.sleep(3)
    abort()


def warn(msg: str, **kwargs):
    """Print an error message to stderr and stop the script.

    To make it distinct in the terminal output, messages are prefixed with 'ERROR: '.

    """
    stderr(f"WARNING: {msg}", **kwargs)
    # wait so users have a chance to see the message before it gets swamped by stdout
    time.sleep(1)


# Start by checking the Python version, older Pythons may not be able to run
# this script.
MINIMUM_PYTHON_VERSION = "3.10"
if sys.version < MINIMUM_PYTHON_VERSION:
    error(f"Firedrake requires Python {MINIMUM_PYTHON_VERSION} or greater")


import argparse
import dataclasses
import enum
import os
import platform
import subprocess
from collections.abc import Mapping, Sequence


# Attributes that we expect to change occasionally

SUPPORTED_PETSC_VERSION = "v3.25.0"
# CUDA 13.1 is currently not supported by GPU drivers on Firedrake CI systems.
SUPPORTED_CUDA_VERSION = "13.0"


def main():
    parser = argparse.ArgumentParser(
        description="""\
Print out the configuration options needed to install Firedrake.

This script takes in arguments declaring the operating system, target
configuration (termed 'ARCH') and install step (installing system packages,
PETSc 'configure', or preparing the environment for 'pip install') and simply
prints options to the screen so they can be passed to the external command.

If a supported operating system (Ubuntu or macOS with homebrew) is detected
then 'firedrake-configure' will specify additional system packages to install
that are used inside PETSc 'configure' instead of building from source.

Please see https://firedrakeproject.org/install for more information."""
    )
    package_manager_group = parser.add_mutually_exclusive_group()
    package_manager_group.add_argument(
        "--package-manager",
        choices=[os_.value for os_ in OS],
        required=False,
        help="The system package manager, if not provided 'firedrake-configure' "
        "will attempt to guess it.",
    )
    package_manager_group.add_argument(
        "--no-package-manager",
        action="store_true",
        required=False,
        help="Do not attempt to use a system package manager.",
    )
    parser.add_argument(
        "--arch",
        choices=[arch.value for arch in ScalarType],
        default=ScalarType.DEFAULT,
        help="The target configuration to install.",
    )
    parser.add_argument(
        "--gpu-arch",
        choices=[arch.value for arch in GPUPlatform],
        default="none",
        help=(
            "Target GPU architecture. WARNING: This is an experimental feature. "
            "GPU support in Firedrake is currently very limited."
        ),
    )
    cmd_group = parser.add_mutually_exclusive_group(required=True)
    cmd_group.add_argument(
        "--show-system-packages",
        "--sysdeps",  # alias
        action="store_true",
        help=(
            "Print out the system packages Firedrake needs including those "
            "expected by PETSc."
        ),
    )
    cmd_group.add_argument(
        "--show-minimal-system-packages",
        action="store_true",
        help=(
            "Print out the minimal system packages Firedrake needs to build. "
            "The user must install these."
        ),
    )
    cmd_group.add_argument(
        "--show-petsc-configure-options",
        "--petscconf",  # alias
        action="store_true",
        help="Print out arguments to pass to PETSc configure.",
    )
    cmd_group.add_argument(
        "--show-petsc-version",
        "--petscver",  # alias
        action="store_true",
        help="Print out the officially supported PETSc version tag.",
    )
    cmd_group.add_argument(
        "--show-env",
        "--env",  # alias
        action="store_true",
        help="Print out the environment variables that need to be exported to install Firedrake.",
    )
    cmd_group.add_argument(
        "--show-extra-repo-pkg-url",
        "--repopkgurl",
        action="store_true",
        help="Print out the URL of any package required to enable non-OS repo access for this build",
    )

    args = parser.parse_args()
    if args.package_manager is not None:
        assert not args.no_package_manager
        os_ = OS(args.package_manager)
    elif args.no_package_manager:
        os_ = OS.UNKNOWN
    else:
        os_ = sniff_package_manager()
    scalar_type = ScalarType(args.arch)

    gpu_platform = GPUPlatform(args.gpu_arch)
    if gpu_platform != GPUPlatform.NO_GPU and os_ == OS.MACOS_ARM64:
        error(
            "GPU-compatible PETSc builds are currently only supported"
            "on Linux"
        )
        abort()

    arch_id = (os_, scalar_type, gpu_platform)

    # TODO: clean up this logic
    if arch_id in SUPPORTED_ARCHS:
        arch = SUPPORTED_ARCHS[arch_id]
    elif arch_id in COMMUNITY_ARCHS:
        raise NotImplementedError("TODO")
    elif os_ == OS.UNKNOWN:
        arch = UNKNOWN_ARCHS[arch_id]
    else:
        error("arch not found")

    if args.show_system_packages:
        # TODO: Move into the arch itself?
        if os_ == OS.UNKNOWN:
            error(
                "Cannot install Firedrake dependencies without a package manager, "
                "please install them manually"
            )
        arch.show_system_packages()
    elif args.show_petsc_configure_options:
        arch.show_petsc_configure_options()
    elif args.show_petsc_version:
        pipe(SUPPORTED_PETSC_VERSION, end="")
    elif args.show_extra_repo_pkg_url:
        arch.show_url()
    else:
        assert args.show_env
        arch.show_env()


class OS(enum.Enum):
    UBUNTU_2404_X86_64 = "ubuntu24.04-x86_64"
    UBUNTU_2404_AARCH64 = "ubuntu24.04-aarch64"
    MACOS_ARM64 = "macos-arm64"
    UNKNOWN = "unknown"


class ScalarType(enum.Enum):
    DEFAULT = "default"
    COMPLEX = "complex"


class GPUPlatform(enum.Enum):
    NO_GPU = "none"
    CUDA = "cuda"


@dataclasses.dataclass(frozen=True, kw_only=True)
class Arch:
    name: str
    system_packages: Sequence[str]
    extra_petsc_configure_options: Sequence[str]
    cflags: Sequence[str]
    cxxflags: Sequence[str]
    fflags: Sequence[str]
    include_dirs: Sequence[str] = ()
    library_dirs: Sequence[str] = ()
    extra_env_vars: Mapping[str, str] = dataclasses.field(default_factory=dict)
    extra_url: str | None = None
    """The URL to a deb package that will enable vendor-specific software development
    repositories, or None if not required.
    """

    common_petsc_configure_options = [
        "--with-c2html=0",
        "--with-debugging=0",
        "--with-fortran-bindings=0",
        "--with-shared-libraries=1",
        "--with-strict-petscerrorcode",
    ]

    def show_system_packages(self) -> None:
        pipe(" ".join(self.system_packages+self.petsc_extras_system_packages), end="")

    def show_petsc_configure_options(self) -> None:
        include_dirs = [f"-I{idir}" for idir in self.include_dirs]
        library_dirs = [f"-L{ldir}" for ldir in self.library_dirs]
        cflags = " ".join((*self.cflags, *include_dirs, *library_dirs))
        cxxflags = " ".join((*self.cxxflags, *include_dirs, *library_dirs))
        fflags = " ".join((*self.fflags, *include_dirs, *library_dirs))
        opts = [
            f"PETSC_ARCH={self.name}",
            f"--COPTFLAGS='{cflags}'",
            f"--CXXOPTFLAGS='{cxxflags}'",
            f"--FOPTFLAGS='{fflags}'",
            *self.common_petsc_configure_options,
            *self.extra_petsc_configure_options,
        ]
        pipe(" ".join(opts), end="")

    def show_url(self) -> None:
        assert self.extra_url
        pipe(self.extra_url, end="")

    def show_env(self) -> None:
        # TODO: inspect the current directory and error if PETSc isn't found
        petsc_dir = f"{os.getcwd()}/petsc",
        petsc_arch = self.name

        def replace_petsc_vars(value: str):
            return value.replace("$PETSC_DIR", petsc_dir).replace("$PETSC_ARCH", petsc_arch)

        env = {
            "PETSC_DIR": petsc_dir,
            "PETSC_ARCH": petsc_arch,
            "HDF5_MPI": "ON",
        }
        env |= self.extra_env_vars
        env_str = " ".join(f"{name}={replace_petsc_vars(value)}" for name, value in env.items())
        pipe(env_str, end="")


ArchID = tuple[OS, ScalarType, GPUPlatform]


# Configurations with official support that are tested in CI
SUPPORTED_ARCHS: Mapping[ArchID, Arch] = {

    # Ubuntu 24.04 x86

    (OS.UBUNTU_2404_X86_64, ScalarType.DEFAULT, GPUPlatform.NO_GPU): Arch(
        name="arch-firedrake-default",
        system_packages=[
            "bison",
            "build-essential",
            "cmake",
            "flex",
            "gfortran",
            "git",
            "ninja-build",
            "pkg-config",
            "python3-dev",
            "python3-pip",

            # PETSc external packages
            "libfftw3-dev",
            "libfftw3-mpi-dev",
            "libhwloc-dev",
            "libhdf5-mpi-dev",
            "libmumps-ptscotch-dev",
            "libmetis-dev",
            "libnetcdf-dev",
            "libopenblas-dev",
            "libopenmpi-dev",
            "libpnetcdf-dev",
            "libptscotch-dev",
            "libscalapack-openmpi-dev",
            "libsuitesparse-dev",
            "libsuperlu-dev",
            "libsuperlu-dist-dev",
        ],
        extra_petsc_configure_options=[
            "--with-bison",
            "--with-fftw",
            "--with-hdf5",
            "--with-hwloc",
            "--with-metis",
            "--with-mumps",
            "--with-netcdf",
            "--with-pnetcdf",
            "--with-ptscotch",
            "--with-scalapack-lib=-lscalapack-openmpi",
            "--with-suitesparse",
            "--with-superlu_dist",
            "--with-zlib",
            "--download-hypre",
        ],
        cflags=["-O3", "-march=native", "-mtune=native"],
        cxxflags=["-O3", "-march=native", "-mtune=native"],
        fflags=["-O3", "-march=native", "-mtune=native"],
        include_dirs=[
            "/usr/include/hdf5/openmpi",
            "/usr/include/scotch",
            "/usr/include/superlu",
            "/usr/include/superlu-dist",
        ],
        library_dirs=[
            "/usr/lib/x86_64-linux-gnu/hdf5/openmpi",
        ],
    ),

    (OS.UBUNTU_2404_X86_64, ScalarType.DEFAULT, GPUPlatform.CUDA): Arch(
        name="arch-firedrake-default-cuda",
        system_packages=[
            "bison",
            "build-essential",
            "cmake",
            "flex",
            "gfortran",
            "git",
            "ninja-build",
            "pkg-config",
            "python3-dev",
            "python3-pip",

            # PETSc external packages
            "libfftw3-dev",
            "libfftw3-mpi-dev",
            "libhwloc-dev",
            "libhdf5-mpi-dev",
            "libmumps-ptscotch-dev",
            "libmetis-dev",
            "libnetcdf-dev",
            "libopenblas-dev",
            "libopenmpi-dev",
            "libpnetcdf-dev",
            "libptscotch-dev",
            "libscalapack-openmpi-dev",

            # CUDA packages
            f"cuda-compat-{SUPPORTED_CUDA_VERSION.replace(".", "-")}",
            f"cuda-nvtx-{SUPPORTED_CUDA_VERSION.replace(".", "-")}",
            f"cuda-cudart-dev-{SUPPORTED_CUDA_VERSION.replace(".", "-")}",
            f"cuda-command-line-tools-{SUPPORTED_CUDA_VERSION.replace(".", "-")}",
            f"cuda-minimal-build-{SUPPORTED_CUDA_VERSION.replace(".", "-")}",
            f"cuda-libraries-dev-{SUPPORTED_CUDA_VERSION.replace(".", "-")}",
            f"cuda-nvml-dev-{SUPPORTED_CUDA_VERSION.replace(".", "-")}",
            f"libnpp-dev-{SUPPORTED_CUDA_VERSION.replace(".", "-")}",
            f"libcusparse-dev-{SUPPORTED_CUDA_VERSION.replace(".", "-")}",
            f"libcublas-dev-{SUPPORTED_CUDA_VERSION.replace(".", "-")}",
        ],
        extra_petsc_configure_options=[
            "--with-bison",
            "--with-fftw",
            "--with-hdf5",
            "--with-hwloc",
            "--with-metis",
            "--with-mumps",
            "--with-netcdf",
            "--with-pnetcdf",
            "--with-ptscotch",
            "--with-scalapack-lib=-lscalapack-openmpi",
            "--with-zlib",
            "--download-hypre",
            "--download-suitesparse",
            "--download-superlu_dist",

            # CUDA options
            "--with-cuda=1",
            "--with-openmp=1",
            "--with-cxx-dialect=c++17",
            "--download-umpire",
        ],
        cflags=["-O3", "-march=native", "-mtune=native"],
        cxxflags=["-O3", "-march=native", "-mtune=native"],
        fflags=["-O3", "-march=native", "-mtune=native"],
        include_dirs=[
            "/usr/include/hdf5/openmpi",
            "/usr/include/scotch",
            "/usr/include/superlu",
            "/usr/include/superlu-dist",
        ],
        library_dirs=[
            "/usr/lib/x86_64-linux-gnu/hdf5/openmpi",
        ],
        extra_env_vars={
            "PATH": f"/usr/local/cuda/bin:{os.environ.get('PATH', '')}",
        },
        extra_url="https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2404/x86_64/cuda-keyring_1.1-1_all.deb",
    ),

    (OS.UBUNTU_2404_X86_64, ScalarType.COMPLEX, GPUPlatform.NO_GPU): Arch(
        name="arch-firedrake-complex",
        system_packages=[
            "bison",
            "build-essential",
            "cmake",
            "flex",
            "gfortran",
            "git",
            "ninja-build",
            "pkg-config",
            "python3-dev",
            "python3-pip",

            # PETSc external packages
            "libfftw3-dev",
            "libfftw3-mpi-dev",
            "libhwloc-dev",
            "libhdf5-mpi-dev",
            "libmumps-ptscotch-dev",
            "libmetis-dev",
            "libnetcdf-dev",
            "libopenblas-dev",
            "libopenmpi-dev",
            "libpnetcdf-dev",
            "libptscotch-dev",
            "libscalapack-openmpi-dev",
            "libsuitesparse-dev",
            "libsuperlu-dev",
            "libsuperlu-dist-dev",
        ],
        extra_petsc_configure_options=[
            "--with-scalar-type=complex",
            "--with-bison",
            "--with-fftw",
            "--with-hdf5",
            "--with-hwloc",
            "--with-metis",
            "--with-mumps",
            "--with-netcdf",
            "--with-pnetcdf",
            "--with-ptscotch",
            "--with-scalapack-lib=-lscalapack-openmpi",
            "--with-suitesparse",
            "--with-superlu_dist",
            "--with-zlib",
        ],
        cflags=["-O3", "-march=native", "-mtune=native"],
        cxxflags=["-O3", "-march=native", "-mtune=native"],
        fflags=["-O3", "-march=native", "-mtune=native"],
        include_dirs=[
            "/usr/include/hdf5/openmpi",
            "/usr/include/scotch",
            "/usr/include/superlu",
            "/usr/include/superlu-dist",
        ],
        library_dirs=[
            "/usr/lib/x86_64-linux-gnu/hdf5/openmpi",
        ],
    ),

    # Ubuntu 24.04 aarch64

    (OS.UBUNTU_2404_AARCH64, ScalarType.DEFAULT, GPUPlatform.NO_GPU): Arch(
        name="arch-firedrake-default",
        system_packages=[
            "bison",
            "build-essential",
            "cmake",
            "flex",
            "gfortran",
            "git",
            "ninja-build",
            "pkg-config",
            "python3-dev",
            "python3-pip",

            # PETSc external packages
            "libfftw3-dev",
            "libfftw3-mpi-dev",
            "libhwloc-dev",
            "libhdf5-mpi-dev",
            "libmumps-ptscotch-dev",
            "libmetis-dev",
            "libnetcdf-dev",
            "libopenblas-dev",
            "libopenmpi-dev",
            "libpnetcdf-dev",
            "libptscotch-dev",
            "libscalapack-openmpi-dev",
            "libsuitesparse-dev",
            "libsuperlu-dev",
            "libsuperlu-dist-dev",
        ],
        extra_petsc_configure_options=[
            "--with-bison",
            "--with-fftw",
            "--with-hdf5",
            "--with-hwloc",
            "--with-metis",
            "--with-mumps",
            "--with-netcdf",
            "--with-pnetcdf",
            "--with-ptscotch",
            "--with-scalapack-lib=-lscalapack-openmpi",
            "--with-suitesparse",
            "--with-superlu_dist",
            "--with-zlib",
            "--download-hypre",
        ],
        cflags=["-O3", "-march=native", "-mtune=native"],
        cxxflags=["-O3", "-march=native", "-mtune=native"],
        fflags=["-O3", "-march=native", "-mtune=native"],
        include_dirs=[
            "/usr/include/hdf5/openmpi",
            "/usr/include/scotch",
            "/usr/include/superlu",
            "/usr/include/superlu-dist",
        ],
        library_dirs=[
            "/usr/lib/aarch64-linux-gnu/hdf5/openmpi",
        ],
    ),

    (OS.UBUNTU_2404_AARCH64, ScalarType.COMPLEX, GPUPlatform.NO_GPU): Arch(
        name="arch-firedrake-complex",
        system_packages=[
            "bison",
            "build-essential",
            "cmake",
            "flex",
            "gfortran",
            "git",
            "ninja-build",
            "pkg-config",
            "python3-dev",
            "python3-pip",

            # PETSc external packages
            "libfftw3-dev",
            "libfftw3-mpi-dev",
            "libhwloc-dev",
            "libhdf5-mpi-dev",
            "libmumps-ptscotch-dev",
            "libmetis-dev",
            "libnetcdf-dev",
            "libopenblas-dev",
            "libopenmpi-dev",
            "libpnetcdf-dev",
            "libptscotch-dev",
            "libscalapack-openmpi-dev",
            "libsuitesparse-dev",
            "libsuperlu-dev",
            "libsuperlu-dist-dev",
        ],
        extra_petsc_configure_options=[
            "--with-scalar-type=complex",
            "--with-bison",
            "--with-fftw",
            "--with-hdf5",
            "--with-hwloc",
            "--with-metis",
            "--with-mumps",
            "--with-netcdf",
            "--with-pnetcdf",
            "--with-ptscotch",
            "--with-scalapack-lib=-lscalapack-openmpi",
            "--with-suitesparse",
            "--with-superlu_dist",
            "--with-zlib",
        ],
        cflags=["-O3", "-march=native", "-mtune=native"],
        cxxflags=["-O3", "-march=native", "-mtune=native"],
        fflags=["-O3", "-march=native", "-mtune=native"],
        include_dirs=[
            "/usr/include/hdf5/openmpi",
            "/usr/include/scotch",
            "/usr/include/superlu",
            "/usr/include/superlu-dist",
        ],
        library_dirs=[
            "/usr/lib/aarch64-linux-gnu/hdf5/openmpi",
        ],
    ),

    # macOS arm64

    (OS.MACOS_ARM64, ScalarType.DEFAULT, GPUPlatform.NO_GPU): Arch(
        name="arch-firedrake-default",
        system_packages=[
            "autoconf",
            "automake",
            "boost",
            "gcc",
            "libtool",
            "make",
            "ninja",
            "pkg-config",
            "python",

            # PETSc external packages
            "cmake",
            "fftw",
            "hwloc",
            "hdf5-mpi",
            "metis",
            "openblas"
            "openmpi",
            "pnetcdf",
            "scalapack",
            "suitesparse",
            "zlib",
        ],
        extra_petsc_configure_options=[
            # External packages
            "--with-fftw-dir=/opt/homebrew",
            "--with-hdf5-dir=/opt/homebrew",
            "--with-hwloc-dir=/opt/homebrew",
            "--with-metis-dir=/opt/homebrew",
            "--with-pnetcdf-dir=/opt/homebrew",
            "--with-scalapack-dir=/opt/homebrew",
            "--with-suitesparse-dir=/opt/homebrew",
            "--with-zlib-dir=/opt/homebrew",
            "--download-bison",
            "--download-hypre",
            "--download-mumps",
            "--download-netcdf",
            "--download-ptscotch",
            "--download-superlu_dist",

            # Avoid macos + openmpi + mumps segmentation violation issue;
            # see https://github.com/firedrakeproject/firedrake/issues/4102 and https://github.com/firedrakeproject/firedrake/issues/4113.
            "-download-mumps-avoid-mpi-in-place",
        ],
        cflags=["-O3", "-march=native", "-mtune=native"],
        cxxflags=["-O3", "-march=native", "-mtune=native"],
        fflags=["-O3"],
        extra_env_vars={"HDF5_DIR": "/opt/homebrew"},
    ),

    (OS.MACOS_ARM64, ScalarType.COMPLEX, GPUPlatform.NO_GPU): Arch(
        name="arch-firedrake-complex",
        system_packages=[
            "autoconf",
            "automake",
            "boost",
            "gcc",
            "libtool",
            "make",
            "ninja",
            "pkg-config",
            "python",

            # PETSc external packages
            "cmake",
            "fftw",
            "hwloc",
            "hdf5-mpi",
            "metis",
            "openblas"
            "openmpi",
            "pnetcdf",
            "scalapack",
            "suitesparse",
            "zlib",
        ],
        extra_petsc_configure_options=[
            "--with-scalar-type=complex",

            # External packages
            "--with-fftw-dir=/opt/homebrew",
            "--with-hdf5-dir=/opt/homebrew",
            "--with-hwloc-dir=/opt/homebrew",
            "--with-metis-dir=/opt/homebrew",
            "--with-pnetcdf-dir=/opt/homebrew",
            "--with-scalapack-dir=/opt/homebrew",
            "--with-suitesparse-dir=/opt/homebrew",
            "--with-zlib-dir=/opt/homebrew",
            "--download-bison",
            "--download-mumps",
            "--download-netcdf",
            "--download-ptscotch",
            "--download-superlu_dist",

            # Avoid macos + openmpi + mumps segmentation violation issue;
            # see https://github.com/firedrakeproject/firedrake/issues/4102 and https://github.com/firedrakeproject/firedrake/issues/4113.
            "-download-mumps-avoid-mpi-in-place",
        ],
        cflags=["-O3", "-march=native", "-mtune=native"],
        cxxflags=["-O3", "-march=native", "-mtune=native"],
        fflags=["-O3"],
        extra_env_vars={"HDF5_DIR": "/opt/homebrew"},
    ),
}


# 'Best effort' configurations that are not tested in CI

# TODO
# class CommunityArch(Arch):
#     maintainer: str
#     last_modified: str
#     ...


# COMMUNITY_ARCHS: Mapping[ArchID, CommunityArch] = {}
COMMUNITY_ARCHS = {}


# TODO
# class UnknownArch(Arch):
#     def show_system_packages(self):
#         error("no")


# Sane default configurations for unknown platforms

# maybe the key should just be scalartype, gpu?
# UNKNOWN_ARCHS: Mapping[ArchID, UnknownArch] = {
UNKNOWN_ARCHS: Mapping[ArchID, Arch] = {

    (OS.UNKNOWN, ScalarType.DEFAULT, GPUPlatform.NO_GPU): Arch(
        name="arch-firedrake-default",
        extra_petsc_configure_options=[
            "--download-bison",
            "--download-fftw",
            "--download-hdf5",
            "--download-hwloc",
            "--download-hypre",
            "--download-metis",
            "--download-mumps",
            "--download-netcdf",
            "--download-pnetcdf",
            "--download-ptscotch",
            "--download-scalapack",
            "--download-suitesparse",
            "--download-superlu_dist",
            "--download-zlib",
        ],
        cflags=["-O3", "-march=native", "-mtune=native"],
        cxxflags=["-O3", "-march=native", "-mtune=native"],
        fflags=["-O3", "-march=native", "-mtune=native"],
        extra_env_vars={"HDF5_DIR": "$PETSC_DIR/$PETSC_ARCH"},
    ),

    (OS.UNKNOWN, ScalarType.COMPLEX, GPUPlatform.NO_GPU): Arch(
        name="arch-firedrake-complex",
        extra_petsc_configure_options=[
            "--with-scalar-type=complex",
            "--download-bison",
            "--download-fftw",
            "--download-hdf5",
            "--download-hwloc",
            "--download-hypre",
            "--download-metis",
            "--download-mumps",
            "--download-netcdf",
            "--download-pnetcdf",
            "--download-ptscotch",
            "--download-scalapack",
            "--download-suitesparse",
            "--download-superlu_dist",
            "--download-zlib",
        ],
        cflags=["-O3", "-march=native", "-mtune=native"],
        cxxflags=["-O3", "-march=native", "-mtune=native"],
        fflags=["-O3", "-march=native", "-mtune=native"],
        extra_env_vars={"HDF5_DIR": "$PETSC_DIR/$PETSC_ARCH"},
    ),
}


def sniff_package_manager() -> OS:
    if platform.system() == "Linux":
        if has_apt():
            if platform.machine() == "x86_64":
                return OS.UBUNTU_2404_X86_64
            elif platform.machine() == "aarch64":
                return OS.UBUNTU_2404_AARCH64
    elif platform.system() == "Darwin":
        if has_homebrew():
            if platform.machine() == "arm64":
                return OS.MACOS_ARM64
    error(
        "No package manager detected, if you want to configure Firedrake without "
        "any system packages please pass '--no-package-manager'"
    )
    abort()


def has_apt() -> bool:
    try:
        subprocess.run(["apt", "--version"], capture_output=True)
    except FileNotFoundError:
        return False
    except:  # noqa: E722
        error("Unexpected error occurred searching for apt")
    else:
        return True


def has_homebrew() -> bool:
    try:
        subprocess.run(["brew", "--version"], capture_output=True)
    except FileNotFoundError:
        return False
    except:  # noqa: E722
        error("Unexpected error occurred searching for homebrew")
    else:
        return True


if __name__ == "__main__":
    main()
