#!/usr/bin/env python3

import enum
import fnmatch
import pathlib
import platform
import subprocess


class System(enum.Enum):
    LINUX = enum.auto()
    MACOS = enum.auto()
    UNKNOWN = enum.auto()


class Arch(enum.Enum):
    X86_64 = enum.auto()
    ARM64 = enum.auto()
    UNKNOWN = enum.auto()


def sniff_platform() -> tuple[System, Arch]:
    system = None
    arch = None
    if platform.system() == "Linux":
        system = System.LINUX
        if platform.machine() == "x86_64":
            arch = Arch.X86_64
        elif platform.machine() == "aarch64":
            arch = Arch.ARM64
    elif platform.system() == "Darwin":
        system = System.MACOS
        if platform.machine() == "arm64":
            arch = Arch.ARM64

    if system is None:
        system = System.UNKNOWN
    if arch is None:
        arch = Arch.UNKNOWN

    return (system, arch)


DEFAULT_CONFIGURE_OPTIONS = (
    "PETSC_ARCH=firedrake",
    "--with-c2html=0",
    "--with-debugging=0",
    "--with-fortran-bindings=0",
    "--with-shared-libraries=1",
    "--with-strict-petscerrorcode",
    "--COPTFLAGS=-O3 -march=native -mtune=native",
    "--CXXOPTFLAGS=-O3 -march=native -mtune=native",
    "--FOPTFLAGS=-O3 -march=native -mtune=native",
)

EXTERNAL_PACKAGES = (
    "fftw",
    "hdf5",
    "hwloc",
    "hypre",
    "metis",
    "mumps",
    "netcdf",
    "pastix",
    "pnetcdf",
    "ptscotch",
    "scalapack",
    "suitesparse",
    "superlu_dist",
    "zlib",
)

APT_INSTALLED_EXTERNAL_PACKAGES = {
    "fftw": None,
    "hdf5": (
        # amd64
        ("/usr/include/hdf5/openmpi", "/usr/lib/x86_64-linux-gnu/hdf5/openmpi/libhdf5.a"),
        # arm64
        ("/usr/include/hdf5/openmpi", "/usr/lib/aarch64-linux-gnu/hdf5/openmpi/libhdf5.a"),
    ),
    "hwloc": None,
    "hypre": (
        # amd64
        ("/usr/include/hypre", "/usr/lib/x86_64-linux-gnu/libHYPRE.a"),
        # arm64
        ("/usr/include/hypre", "/usr/lib/aarch64-linux-gnu/libHYPRE.a"),
    ),
    "zlib": None,
}


package_manager = "apt"

configure_options = list(DEFAULT_CONFIGURE_OPTIONS)

# NOTE: Need to think about interface, when to sniff this or make it configurable, fallbacks?
system, arch = sniff_platform()

if package_manager == "apt":
    assert system == System.LINUX

    for external_package in EXTERNAL_PACKAGES:
        if external_package in APT_INSTALLED_EXTERNAL_PACKAGES:
            package_spec = APT_INSTALLED_EXTERNAL_PACKAGES[external_package]
            if package_spec is None:
                # PETSc will find the package for us
                configure_options.append(f"--with-{external_package}")
            else:
                if arch == Arch.X86_64:
                    package_spec = package_spec[0]
                else:
                    assert arch == Arch.ARM64
                    package_spec = package_spec[1]

                # Have to provide paths for headers and libraries
                (include_dir, lib) = package_spec
                configure_options.append(f"--with-{external_package}-include={include_dir}")
                configure_options.append(f"--with-{external_package}-lib={lib}")
        else:
            # Package not provided by package manager, download it instead
            configure_options.append(f"--download-{external_package}")

elif package_manager == "homebrew":
    raise NotImplementedError("TODO")
else:
    assert package_manager is None
    for external_package in EXTERNAL_PACKAGES:
        configure_options.append(f"--download-{external_package}")

print(" ".join(configure_options), end="")
