#!/usr/bin/env python3

import firedrake_configuration
firedrake_configuration.setup_cache_dirs()
from firedrake.tsfc_interface import clear_cache, TSFCKernel
from pyop2.compilation import clear_cache as pyop2_clear_cache


if __name__ == '__main__':
    print('Removing cached TSFC kernels from %s' % TSFCKernel._cachedir)
    clear_cache()
    pyop2_clear_cache()
