input: clean
	demo/meshes/generate_mesh a 20
	demo/meshes/generate_mesh b 40
	demo/meshes/generate_mesh c 80
	demo/meshes/generate_mesh d 160

.PHONY: clean input
clean:
	@rm -f *.out *.geo *.edge *.ele *.msh *.node *.pyc
