name: Reusable Docker workflow

# This workflow merges Linux and macOS images and pushes them to Docker.
# See https://docs.docker.com/build/ci/github-actions/multi-platform/ for more information.

on:
  workflow_call:
    inputs:
      target:
        description: 'Target docker image name to upload to'
        required: true
        type: string
      tag:
        description: 'Optional tag (defaults to `latest`)'
        required: false
        default: 'latest'
        type: string
    secrets:
      # Docker login information
      DOCKERHUB_USER:
        required: true
      DOCKERHUB_TOKEN:
        required: true

jobs:
  docker_merge:
    runs-on: [self-hosted, Linux]
    steps:
      - name: Pre-cleanup
        if: always()
        run: |
          rm -rf ${{ runner.temp }}/digests

      - name: Download digests
        uses: actions/download-artifact@v4
        with:
          path: ${{ runner.temp }}/digests
          pattern: digests_${{ inputs.target }}_*
          merge-multiple: true

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Merge and push the per-platform images
        working-directory: ${{ runner.temp }}/digests
        run: |
          docker buildx imagetools create -t firedrakeproject/${{ inputs.target }}:${{ inputs.tag }} $(printf 'firedrakeproject/${{ inputs.target }}@sha256:%s ' *)

      - name: Inspect image
        run: |
          docker buildx imagetools inspect firedrakeproject/${{ inputs.target }}:${{ inputs.tag }}

      - name: Post-cleanup
        if: always()
        run: |
          rm -rf ${{ runner.temp }}/digests
