name: Reusable Docker workflow

on:
  workflow_call:
    inputs:
      target:
        description: 'Target docker image name to upload to'
        required: true
        type: string
      tag:
        description: 'Optional tag (defaults to `latest`)'
        required: false
        default: 'latest'
        type: string
      dockerfile:
        description: 'Path to the dockerfile required to build image'
        required: true
        type: string
    secrets:
      # Docker login information
      DOCKERHUB_USER:
        required: true
      DOCKERHUB_TOKEN:
        required: true

jobs:
  docker_workflow:
    name: "Build the ${{ inputs.target }} container"
    runs-on: self-hosted
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push ${{ inputs.target }}
        uses: docker/build-push-action@v4
        with:
          push: true
          no-cache: true
          file: ${{ inputs.dockerfile }}
          tags: firedrakeproject/${{ inputs.target }}:${{ inputs.tag }}
