name: Run lint

on:
  # Push to master or PR
  push:
    branches:
      - master
  pull_request:

jobs:
  linter:
    name: "Run linter"
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as
    # part of the jobs
    steps:
      - uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install linter
        run: |
          pip install flake8 pylint
      - name: Lint codebase
        run: |
          make lint
      - name: Install bibtex linter
        run: |
          pip install bibtexparser
      - name: Check bibtex
        run: |
          cd docs
          make validate-bibtex
      - name: Install YAML linter
        run: |
          pip install yamllint
      - name: Lint YAML files
        run: |
          yamllint -f github .github/workflows/*.yml
  docker_linter:
    name: "Lint dockerfiles"
    runs-on: ubuntu-latest
    container:
      image: hadolint/hadolint:latest-alpine
      env:
        HADOLINT_IGNORE: "DL3005,DL3007,DL3008,DL3015,DL3059"
    steps:
      - uses: actions/checkout@v3
      - name: Lint dockerfiles inside hadolint container
        run: |
          for DOCKERFILE in docker/Dockerfile.*; \
            do \
            echo "    Linting $DOCKERFILE"; \
            hadolint $DOCKERFILE \
            || exit 1; \
          done
