name: Test pull request

on:
  pull_request:
    types: [ opened, synchronize, reopened, labeled, unlabeled ]

jobs:
  test:
    uses: ./.github/workflows/core.yml
    with:
      trigger: pr
      source_ref: ${{ github.ref }}
      # If not the actual target of the PR, the target branch ('main' or 'release')
      # can be set with an appropriate label ('base:main' or 'base:release')
      base_ref: |-
        ${{ case(
          contains(github.event.pull_request.labels.*.name, 'base:main'), 'main',
          contains(github.event.pull_request.labels.*.name, 'base:release'), 'release',
          github.base_ref == 'main', 'main',
          github.base_ref == 'release', 'release',
          'INVALID_BASE_REF'
        ) }}
      # Run all tests of a specific configuration (e.g. complex) if the right label
      # is on the PR, otherwise do nothing.
      test_complex: ${{ contains(github.event.pull_request.labels.*.name, 'ci:complex') }}
      test_64bit: ${{ contains(github.event.pull_request.labels.*.name, 'ci:64bit') }}
      test_cuda: ${{ contains(github.event.pull_request.labels.*.name, 'ci:cuda') }}
      test_macos: ${{ contains(github.event.pull_request.labels.*.name, 'ci:macos') }}
    secrets: inherit
