name: Test pull request

on:
  pull_request:
    types: [ opened, synchronize, reopened, labeled ]

jobs:
  test:
    uses: ./.github/workflows/core.yml
    with:
      source_ref: ${{ github.ref }}
      target_branch: ${{ github.base_ref }}
      # Run all tests of a specific configuration (e.g. complex) if the right label
      # is on the PR, otherwise do nothing.
      test_complex: |-
        ${{ case(
          contains(github.event.pull_request.labels.*.name, 'ci:complex'), 'all',
          'none'
        ) }}
      test_cuda: |-
        ${{ case(
          contains(github.event.pull_request.labels.*.name, 'ci:cuda'), 'all',
          'none'
        ) }}
      test_macos: |-
        ${{ case(
          contains(github.event.pull_request.labels.*.name, 'ci:macos'), 'all',
          'none'
        ) }}
    secrets: inherit
