name: Deploy after push

on:
  push:
    branches:
      - main
      - release

jobs:
  test:
    uses: ./.github/workflows/core.yml
    with:
      source_ref: ${{ github.ref_name }}
      target_branch: ${{ github.ref_name }}
      test_macos: true
      deploy_website: true
    secrets: inherit

  docker:
    name: Build developer Docker containers
    uses: ./.github/workflows/docker.yml
    with:
      tag: dev-${{ github.ref_name }}
      branch: ${{ github.ref_name }}
      build_dev: true
    secrets: inherit

  colab:
    name: Update Colab notebooks
    if: github.ref_name == 'release'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Firedrake
        uses: actions/checkout@v5
        with:
          path: firedrake

      - name: Checkout Colab notebooks
        uses: actions/checkout@v5
        with:
          repository: firedrakeproject/notebooks
          path: notebooks

      - name: Copy notebooks
        run: cp -r firedrake/docs/notebooks/* notebooks/

      - name: Prepare notebooks for Colab
        working-directory: notebooks
        run: ./utils/firedrake-colab-notebooks *.ipynb

      - name: Push changes if needed
        working-directory: notebooks
        run: |
          if [ ! -z "$( git status --porcelain )" ]; then
            git add --all .
            git commit -m "Upstream updates"
            git push
          fi
